### ISSUE TITLE
SourceCodePro + iScript

### ISSUE THREAD

**Issue by sourabhv** [kencrocken/FiraCodeiScript#12]
Hey, this font looks really cool but I'm not a fan of FiraCode. Can you make one with SourceCodePro + iScript or add a how-to section so anyone can mash up 2 fonts of their choice?

[SourceCodePro does allow modification](https://github.com/adobe-fonts/source-code-pro/blob/master/LICENSE.md)

**Comment by kencrocken** [comment]
@sourabhv Thanks for the compliment.  Unfortunately, work has me pretty busy.  Here is a link to a really good write up on how to combine the fonts.  

https://github.com/open-source-ideas/open-source-ideas/issues/10#issuecomment-360999485
