### ISSUE TITLE
Don't work under linux.

### ISSUE THREAD

**Issue by Jeremi360** [kencrocken/FiraCodeiScript#2]
On Ubuntu 16.04 Fira Code iScript Italic looks the same like base Fira Code Italic :(
![image](https://user-images.githubusercontent.com/1294815/33161129-b864ade6-d021-11e7-935c-f083a4e62671.png)

**Comment by kencrocken** [comment]
Sorry about the trouble.   

Make sure all three font files are installed on your system - you may need to reboot after installing.  

Maybe one of the ideas in this link will help, https://askubuntu.com/questions/3697/how-do-i-install-fonts

**Comment by Jeremi360** [comment]
I install every thing right:
```
fc-list | grep "Fira Code iScript"
/home/jeremi360/.fonts/Library/F/FiraCodeiScript-Regular.ttf: Fira Code iScript:style=Regular
/home/jeremi360/.fonts/Library/F/FiraCodeiScript-Italic.ttf: Fira Code iScript:style=Italic
/home/jeremi360/.fonts/Library/F/FiraCodeiScript-Bold.ttf: Fira Code iScript:style=Bold
```

**Comment by Jeremi360** [comment]
Close by accident.

**Comment by andys8** [comment]
Are you still having trouble? I'm using the font for quite a time with vs code and 16.04.

**Comment by kencrocken** [comment]
@andys8 That's great ... I saw some instructions in the original ideas thread where the individual laid out the details and got it working in linux - were you able to get this repo working in Linux?

**Comment by andys8** [comment]
First off all, let's clarify: This is how it looks on my machine and how it should look, right?
![image](https://user-images.githubusercontent.com/13085980/36619643-d96a3db4-18ef-11e8-9f0b-f523781b275e.png)

**Comment by kencrocken** [comment]
@andys8 Looks good to me ..

**Comment by andys8** [comment]
I tried different themes. They behave differently in case which parts are italic and which aren't, but it works. Tested it with "Material Palenight", too.

The fonts are installed in a different folder. The machine I'm using now is Linux Mint.

```sh
fc-list | grep "Fira Code iScript"
/home/as/.local/share/fonts/FiraCodeiScript-Italic.ttf: Fira Code iScript:style=Italic
/home/as/.local/share/fonts/FiraCodeiScript-Bold.ttf: Fira Code iScript:style=Bold
/home/as/.local/share/fonts/FiraCodeiScript-Regular.ttf: Fira Code iScript:style=Regular
```

**Comment by kencrocken** [comment]
@andys8 Thanks!  I'll close this for now ...
